name: Test ci/cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  read_the_file:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Read File
        run: |
          ls -l
          cat app/routes/home.tsx
